# Generated by Django 5.0.3 on 2024-04-28 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookapi", "0002_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="buylingLink",
            new_name="buyinglink",
        ),
    ]
